<a href="https://colab.research.google.com/github/RicardoHG7/Extracci-ndeDatos-/blob/main/Datos_de_facturacion.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Ricardo Herrera Guerrero

In [10]:
#Importamos librer√≠as requeridas
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
#Cargar archivo csv desde equipo
from google.colab import files
files.upload()

In [23]:
#Carga desde un archivo .xlsx sin indice
df = pd.read_excel('Datos.xlsx')
df

,CVE_DOC,CVE_CLPV,STATUS,CVE_VEND,FECHAELAB,FECHA_DOC,FECHA_ENT,FECHA_VEN,FECHA_CANCELA,CAN_TOT,DES_TOT,DES_FIN
0,F29414,2465,C,1.0,2019-09-03 08:58:42.000,2019-09-03,2019-09-03 00:00:00,2019-09-18,2019-09-04,3980.00,0.0,0
1,F29415,3926,C,1.0,2019-09-03 09:55:14.000,2019-09-03,2019-09-03 00:00:00,2019-10-03,2019-09-03,1550.00,0.0,0
2,F29416,3926,C,1.0,2019-09-03 13:25:33.000,2019-09-03,2019-09-03 00:00:00,2019-10-03,2019-09-03,1550.00,0.0,0
3,F29417,3926,C,1.0,2019-09-03 13:33:23.000,2019-09-03,2019-09-03 00:00:00,2019-10-03,2019-09-17,1550.00,0.0,0
4,F29418,6813,C,2.0,2019-09-03 14:23:45.000,2019-09-03,2019-09-03 00:00:00,2019-09-03,2019-09-10,2435.44,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
10890,F40306,8842,E,2.0,2023-03-06 16:09:39.013,2023-03-06,2023-03-01 00:00:00,2023-03-06,NaT,3272.00,0.0,0
10891,F40307,6218,E,2.0,2023-03-06 16:38:42.933,2023-03-06,2023-03-06 00:00:00,2023-03-06,NaT,504.15,0.0,0
10892,F40308,5926,E,2.0,2023-03-06 17:02:33.390,2023-03-06,2023-03-06 00:00:00,2023-03-06,NaT,275.68,0.0,0
10893,F40309,361,E,2.0,2023-03-07 12:43:49.567,2023-03-07,2023-03-07 00:00:00,2023-03-07,NaT,129.30,0.0,0
10894,F40310,3011,E,2.0,2023-03-07 12:45:58.407,2023-03-07,2023-03-01 00:00:00,2023-03-07,NaT,517.20,0.0,0

#CVE_CLPV      (valores: 1000 a 2000)

In [28]:
df['CVE_CLPV'] = pd.to_numeric(df['CVE_CLPV'], errors='coerce')
df1 = df[(df['CVE_CLPV'] >= 1000) & (df['CVE_CLPV'] <= 2000)]
df1

,CVE_DOC,CVE_CLPV,STATUS,CVE_VEND,FECHAELAB,FECHA_DOC,FECHA_ENT,FECHA_VEN,FECHA_CANCELA,CAN_TOT,DES_TOT,DES_FIN
18,F29432,1965.0,C,2.0,2019-09-05 11:05:04.000,2019-09-05,2019-09-05 00:00:00,2019-09-20,2019-09-06,976.50,0.00,0
22,F29436,1965.0,C,2.0,2019-09-06 12:01:36.000,2019-09-06,2019-09-06 00:00:00,2019-09-21,2019-09-12,976.50,0.00,0
65,F29479,1240.0,E,2.0,2019-09-11 18:38:45.000,2019-09-11,2019-09-11 00:00:00,2019-09-11,NaT,4135.00,0.00,0
71,F29485,1965.0,C,2.0,2019-09-12 12:14:28.000,2019-09-12,2019-09-12 00:00:00,2019-09-27,2019-09-12,976.50,146.48,0
72,F29486,1965.0,E,2.0,2019-09-12 12:25:52.000,2019-09-12,2019-09-12 00:00:00,2019-09-27,NaT,976.50,146.48,0
...,...,...,...,...,...,...,...,...,...,...,...,...
10821,F40237,1757.0,E,2.0,2023-02-24 15:18:17.570,2023-02-24,2023-02-13 00:00:00,2023-02-24,NaT,10088.40,0.00,0
10839,F40255,1583.0,E,2.0,2023-02-28 09:15:45.753,2023-02-28,2023-02-28 00:00:00,2023-03-30,NaT,3467.35,0.00,0
10845,F40261,1786.0,E,2.0,2023-02-28 11:15:32.527,2023-02-28,2023-03-03 00:00:00,2023-02-28,NaT,4663.80,0.00,0
10871,F40287,1453.0,E,1.0,2023-03-01 12:58:23.397,2023-03-01,2023-02-27 00:00:00,2023-03-31,NaT,9000.00,0.00,0
10876,F40292,1082.0,E,6.0,2023-03-02 11:00:54.770,2023-03-02,2023-03-01 00:00:00,2023-03-02,NaT,3262.00,0.00,0

In [ ]:
#Convertir archivo filtrado a CSV
df1.to_csv("df1.csv")
#descardar archivo filtrado en csv
from google.colab import files   
files.download("df1.csv")

#CVE_VEND     (Todas las claves excepto ‚Äú5‚Äù y ‚Äú4‚Äù)

In [30]:
df2 = df[~df['CVE_VEND'].isin(['4', '5'])]
df2

,CVE_DOC,CVE_CLPV,STATUS,CVE_VEND,FECHAELAB,FECHA_DOC,FECHA_ENT,FECHA_VEN,FECHA_CANCELA,CAN_TOT,DES_TOT,DES_FIN
18,F29432,1965.0,C,2.0,2019-09-05 11:05:04.000,2019-09-05,2019-09-05 00:00:00,2019-09-20,2019-09-06,976.50,0.00,0
22,F29436,1965.0,C,2.0,2019-09-06 12:01:36.000,2019-09-06,2019-09-06 00:00:00,2019-09-21,2019-09-12,976.50,0.00,0
65,F29479,1240.0,E,2.0,2019-09-11 18:38:45.000,2019-09-11,2019-09-11 00:00:00,2019-09-11,NaT,4135.00,0.00,0
71,F29485,1965.0,C,2.0,2019-09-12 12:14:28.000,2019-09-12,2019-09-12 00:00:00,2019-09-27,2019-09-12,976.50,146.48,0
72,F29486,1965.0,E,2.0,2019-09-12 12:25:52.000,2019-09-12,2019-09-12 00:00:00,2019-09-27,NaT,976.50,146.48,0
...,...,...,...,...,...,...,...,...,...,...,...,...
10821,F40237,1757.0,E,2.0,2023-02-24 15:18:17.570,2023-02-24,2023-02-13 00:00:00,2023-02-24,NaT,10088.40,0.00,0
10839,F40255,1583.0,E,2.0,2023-02-28 09:15:45.753,2023-02-28,2023-02-28 00:00:00,2023-03-30,NaT,3467.35,0.00,0
10845,F40261,1786.0,E,2.0,2023-02-28 11:15:32.527,2023-02-28,2023-03-03 00:00:00,2023-02-28,NaT,4663.80,0.00,0
10871,F40287,1453.0,E,1.0,2023-03-01 12:58:23.397,2023-03-01,2023-02-27 00:00:00,2023-03-31,NaT,9000.00,0.00,0
10876,F40292,1082.0,E,6.0,2023-03-02 11:00:54.770,2023-03-02,2023-03-01 00:00:00,2023-03-02,NaT,3262.00,0.00,0

In [37]:
#Convertir archivo filtrado a CSV
df2.to_csv("df2.csv")
#descardar archivo filtrado en csv
from google.colab import files   
files.download("df2.csv")

#FECHA_ENT   (Fechas de ‚Äú28/02/2022‚Äù)

In [31]:
df3 = df[df['FECHA_ENT'] == '2022-02-28']
df3

Empty DataFrame
Columns: [CVE_DOC, CVE_CLPV, STATUS, CVE_VEND, FECHAELAB, FECHA_DOC, FECHA_ENT, FECHA_VEN, FECHA_CANCELA, CAN_TOT, DES_TOT, DES_FIN]
Index: []

In [38]:
#Convertir archivo filtrado a CSV
df3.to_csv("df3.csv")
#descardar archivo filtrado en csv
from google.colab import files   
files.download("df3.csv")

#CAN_TOT       (Cantidades menores a 5951.7)   o  STATUS (‚ÄúE‚Äù)

In [32]:
df4 = df[(df['CAN_TOT'] < 5951.7) | (df['STATUS'] == 'E')]
df4

,CVE_DOC,CVE_CLPV,STATUS,CVE_VEND,FECHAELAB,FECHA_DOC,FECHA_ENT,FECHA_VEN,FECHA_CANCELA,CAN_TOT,DES_TOT,DES_FIN
18,F29432,1965.0,C,2.0,2019-09-05 11:05:04.000,2019-09-05,2019-09-05 00:00:00,2019-09-20,2019-09-06,976.50,0.00,0
22,F29436,1965.0,C,2.0,2019-09-06 12:01:36.000,2019-09-06,2019-09-06 00:00:00,2019-09-21,2019-09-12,976.50,0.00,0
65,F29479,1240.0,E,2.0,2019-09-11 18:38:45.000,2019-09-11,2019-09-11 00:00:00,2019-09-11,NaT,4135.00,0.00,0
71,F29485,1965.0,C,2.0,2019-09-12 12:14:28.000,2019-09-12,2019-09-12 00:00:00,2019-09-27,2019-09-12,976.50,146.48,0
72,F29486,1965.0,E,2.0,2019-09-12 12:25:52.000,2019-09-12,2019-09-12 00:00:00,2019-09-27,NaT,976.50,146.48,0
...,...,...,...,...,...,...,...,...,...,...,...,...
10821,F40237,1757.0,E,2.0,2023-02-24 15:18:17.570,2023-02-24,2023-02-13 00:00:00,2023-02-24,NaT,10088.40,0.00,0
10839,F40255,1583.0,E,2.0,2023-02-28 09:15:45.753,2023-02-28,2023-02-28 00:00:00,2023-03-30,NaT,3467.35,0.00,0
10845,F40261,1786.0,E,2.0,2023-02-28 11:15:32.527,2023-02-28,2023-03-03 00:00:00,2023-02-28,NaT,4663.80,0.00,0
10871,F40287,1453.0,E,1.0,2023-03-01 12:58:23.397,2023-03-01,2023-02-27 00:00:00,2023-03-31,NaT,9000.00,0.00,0
10876,F40292,1082.0,E,6.0,2023-03-02 11:00:54.770,2023-03-02,2023-03-01 00:00:00,2023-03-02,NaT,3262.00,0.00,0

In [39]:
#Convertir archivo filtrado a CSV
df4.to_csv("df4.csv")
#descardar archivo filtrado en csv
from google.colab import files   
files.download("df4.csv")

#Solo las columnas: CVE_DOC, FECHA_ENT, FECHA_VEN y CAN_TOT

In [33]:
df5 = df[['CVE_DOC', 'FECHA_ENT', 'FECHA_VEN', 'CAN_TOT']]
df5

      CVE_DOC            FECHA_ENT  FECHA_VEN   CAN_TOT
18     F29432  2019-09-05 00:00:00 2019-09-20    976.50
22     F29436  2019-09-06 00:00:00 2019-09-21    976.50
65     F29479  2019-09-11 00:00:00 2019-09-11   4135.00
71     F29485  2019-09-12 00:00:00 2019-09-27    976.50
72     F29486  2019-09-12 00:00:00 2019-09-27    976.50
...       ...                  ...        ...       ...
10821  F40237  2023-02-13 00:00:00 2023-02-24  10088.40
10839  F40255  2023-02-28 00:00:00 2023-03-30   3467.35
10845  F40261  2023-03-03 00:00:00 2023-02-28   4663.80
10871  F40287  2023-02-27 00:00:00 2023-03-31   9000.00
10876  F40292  2023-03-01 00:00:00 2023-03-02   3262.00

[583 rows x 4 columns]

In [40]:
#Convertir archivo filtrado a CSV
df5.to_csv("df5.csv")
#descardar archivo filtrado en csv
from google.colab import files   
files.download("df5.csv")

#Solo las filas de 7001-7099

In [34]:
df6 = df.loc[7000:7098]
df6

,CVE_DOC,CVE_CLPV,STATUS,CVE_VEND,FECHAELAB,FECHA_DOC,FECHA_ENT,FECHA_VEN,FECHA_CANCELA,CAN_TOT,DES_TOT,DES_FIN
7004,F36420,1429.0,E,1.0,2021-10-15 09:01:08.393,2021-10-15,2021-10-15 00:00:00,2021-12-14,NaT,23625.00,0.0,0
7024,F36440,1761.0,E,2.0,2021-10-18 13:03:02.247,2021-10-18,2021-10-18 00:00:00,2021-10-18,NaT,428.71,0.0,0
7063,F36479,1016.0,E,3.0,2021-10-22 09:16:25.793,2021-10-22,2021-10-22 00:00:00,2021-11-21,NaT,4400.00,0.0,0

In [41]:
#Convertir archivo filtrado a CSV
df6.to_csv("df6.csv")
#descardar archivo filtrado en csv
from google.colab import files   
files.download("df6.csv")

#Index= CVE_VEND (valores: 1, 2)  (columna: FECHAELAB)

In [35]:
df7 = df.set_index(['CVE_VEND', 'FECHAELAB'])
df7

                                 CVE_DOC  CVE_CLPV STATUS  FECHA_DOC  \
CVE_VEND FECHAELAB
2.0      2019-09-05 11:05:04.000  F29432    1965.0      C 2019-09-05
         2019-09-06 12:01:36.000  F29436    1965.0      C 2019-09-06
         2019-09-11 18:38:45.000  F29479    1240.0      E 2019-09-11
         2019-09-12 12:14:28.000  F29485    1965.0      C 2019-09-12
         2019-09-12 12:25:52.000  F29486    1965.0      E 2019-09-12
...                                  ...       ...    ...        ...
         2023-02-24 15:18:17.570  F40237    1757.0      E 2023-02-24
         2023-02-28 09:15:45.753  F40255    1583.0      E 2023-02-28
         2023-02-28 11:15:32.527  F40261    1786.0      E 2023-02-28
1.0      2023-03-01 12:58:23.397  F40287    1453.0      E 2023-03-01
6.0      2023-03-02 11:00:54.770  F40292    1082.0      E 2023-03-02

                                            FECHA_ENT  FECHA_VEN  \
CVE_VEND FECHAELAB
2.0      2019-09-05 11:05:04.000  2019-09-05 00:00:00 2019-09-20
         2019-09-06 12:01:36.000  2019-09-06 00:00:00 2019-09-21
         2019-09-11 18:38:45.000  2019-09-11 00:00:00 2019-09-11
         2019-09-12 12:14:28.000  2019-09-12 00:00:00 2019-09-27
         2019-09-12 12:25:52.000  2019-09-12 00:00:00 2019-09-27
...                                               ...        ...
         2023-02-24 15:18:17.570  2023-02-13 00:00:00 2023-02-24
         2023-02-28 09:15:45.753  2023-02-28 00:00:00 2023-03-30
         2023-02-28 11:15:32.527  2023-03-03 00:00:00 2023-02-28
1.0      2023-03-01 12:58:23.397  2023-02-27 00:00:00 2023-03-31
6.0      2023-03-02 11:00:54.770  2023-03-01 00:00:00 2023-03-02

                                 FECHA_CANCELA   CAN_TOT  DES_TOT  DES_FIN
CVE_VEND FECHAELAB
2.0      2019-09-05 11:05:04.000    2019-09-06    976.50     0.00        0
         2019-09-06 12:01:36.000    2019-09-12    976.50     0.00        0
         2019-09-11 18:38:45.000           NaT   4135.00     0.00        0
         2019-09-12 12:14:28.000    2019-09-12    976.50   146.48        0
         2019-09-12 12:25:52.000           NaT    976.50   146.48        0
...                                        ...       ...      ...      ...
         2023-02-24 15:18:17.570           NaT  10088.40     0.00        0
         2023-02-28 09:15:45.753           NaT   3467.35     0.00        0
         2023-02-28 11:15:32.527           NaT   4663.80     0.00        0
1.0      2023-03-01 12:58:23.397           NaT   9000.00     0.00        0
6.0      2023-03-02 11:00:54.770           NaT   3262.00     0.00        0

[583 rows x 10 columns]

In [42]:
#Convertir archivo filtrado a CSV
df7.to_csv("df7.csv")
#descardar archivo filtrado en csv
from google.colab import files   
files.download("df7.csv")